local M = {
  "folke/which-key.nvim",
  event = "VeryLazy",
}

function M.config()
  local mappings = {
    { "<leader>a", group = "Tab" },
    { "<leader>b", group = "Buffers" },
    { "<leader>c", group = "Compiler" },
    { "<leader>d", group = "Debug" },
    { "<leader>f", group = "Find" },
    { "<leader>g", group = "Git" },
    { "<leader>l", group = "LSP" },
    { "<leader>p", group = "Plugins" },
    -- { "<leader>T", group = "Treesitter" },
    { "<leader>t", group = "Test" },
    { "<leader>ah", "<cmd>-tabmove<cr>", desc = "Move Left" },
    { "<leader>al", "<cmd>+tabmove<cr>", desc = "Move Right" },
    { "<leader>aN", "<cmd>tabnew %<cr>", desc = "New Tab" },
    { "<leader>an", "<cmd>$tabnew<cr>", desc = "New Empty Tab" },
    { "<leader>ao", "<cmd>tabonly<cr>", desc = "Only" },
    { "<leader>h", "<cmd>nohlsearch<CR>", desc = "NOHL" },
    { "<leader>q", "<cmd>confirm q<CR>", desc = "Quit" },
    { "<leader>v", "<cmd>vsplit<CR>", desc = "Split" },
    { "<leader>;", "<cmd>tabnew | terminal<CR>", desc = "Terminal" },
  }

  local which_key = require "which-key"
  which_key.setup {
    preset = "helix",
    sort = { "manual", "local", "alphanum", "mod" },
    triggers = {
      { "<auto>", mode = "nixsotc" },
      { "m", mode = "n" },
      { "s", mode = "n" },
      { "c", mode = "n" },
      { "d", mode = "n" },
      { "y", mode = "n" },
    },
    plugins = {
      marks = true,
      registers = true,
      spelling = {
        enabled = true,
        suggestions = 20,
      },
      presets = {
        operators = true,
        motions = false,
        text_objects = false,
        windows = false,
        nav = false,
        z = false,
        g = false,
      },
    },
-- check to ensure that changing window to helix is appropiate, cannot see differences
    win = {
      border = "rounded",
      no_overlap = false,
      padding = { 1, 2},
      title = false,
      title_pos = "center",
      zindex = 1000,
    },
    show_help = false,
    show_keys = false,
    disable = {
      buftypes = {},
      filetypes = { "TelescopePrompt" },
    },
  }

  local wk = require "which-key"
 
  -- icon colors
  -- azure, blue, cyan, green, grey, orange, purple, red, yellow

  wk.add {
    { "<leader>a", group = "AI", icon = { icon = " ", color = "blue" } },
    { "<leader>b", group = "Buffers", icon = { icon = "󰓩 ", color = "blue" }  },
    { "<leader>c", group = "Compiler", desc="Compiler", icon = { icon = "󱁤 ", color = "green" } },
    { "<leader>d", group = "Debug" },
    { "<leader>f", group = "Find", icon = { icon = " ", color = "yellow" } },
    { "<leader>g", group = "Git" },
    { "<leader>h", "<cmd>nohlsearch<CR>", desc = "NOHL", hidden = true },
    { "<leader>l", group = "LSP", icon = { icon = " ", color = "blue" }},
    { "<leader>p", group = "Plugins", icon = { icon = " ", color = "blue" } },
    { "m", group = "Macros", icon = { icon = " ", color = "green" } },
    { "<leader>e", desc = "File Explorer", icon = { icon = "" } },
    { "<leader>q", desc = "Quit", "<cmd>confirm q<CR>"  },
    -- { "<leader>T", desc = "Treesitter", },

    -- { "<leader>la", desc = "LSP"},
    -- { "<leader>le", desc = "LSP"},
    -- { "<leader>lq", desc = "LSP"},
    -- { "<leader>lr", desc = "LSP"},
    -- { "<leader>ll", desc = "LSP"},
    -- { "<leader>lm", desc = "LSP"},
    -- { "<leader>lf", desc = "LSP"},
    -- { "<leader>lh", desc = "LSP"},
    -- { "<leader>li", desc = "LSP"},
    -- { "<leader>lj", desc = "LSP"},
    -- { "<leader>lk", desc = "LSP"},
    { "<leader>o", function() vim.ui.open(vim.fn.expand("<cfile>")) end, desc = "Open URL/File", icon = { icon = " ", color = "blue" } },
    { "<leader>t", desc = "Triforce Stats", "<cmd>Triforce profile<CR>", icon = { icon = "󰄩", color = "blue",}, },
    { "<leader>v", desc = "Split", "<cmd>vsplit<CR>",  icon = { icon = "󰖲", color = "cyan",} },
    { "<leader>w", desc = "Toggle Wrap", "<cmd>lua vim.wo.wrap = not vim.wo.wrap<CR>",  icon = { icon = "󰖶 ", color = "blue" } },
    { "<leader>;", desc = "Terminal", "<cmd>tabnew | terminal<CR>",  icon = { icon = " ", color = "green" } },

    { "g", group = "Go to" },
    { "gd", desc = "Go to Definition", icon = { icon = "󰗚 " } },
    { "gg", desc = "Go to Top of File", icon = { icon = "󰘣 " } },
    { "gl", desc = "Show Line Diagnostics", icon = { icon = " " } },
    { "gm", desc = "Go to Middle of Line", icon = { icon = "󰘞 " } },
    { "gx", desc = "Go to File/URL", icon = { icon = "󰏋 " } },
    { "c", group = "Change" },
    { "caw", desc = "Change around Word"},
    { "ciw", desc = "Change inside Word"},
    { "cs", desc = "Change Surround" },
    { "ct", desc = "Change Surrounding HTML Tag", icon = { icon = " " }, },

    { "d", group = "Delete" },
    { "ds", desc = "Delete Surround" },
    { "dt", desc = "Delete Surrounding HTML Tag", icon = { icon = " " }, },

    { "y", group = "Yank" },
    { "ys", desc = "Yank Surround" },

    { "s",  group = "Surround" },
    { "sb", desc = "Surround with ()", icon = { icon = "󰅲 " }, },
    { "s{", desc = "Surround with {}", icon = { icon = " " }, },
    { "s}", desc = "Surround with {}", icon = { icon = " " }, },
    { "s[", desc = "Surround with {}", icon = { icon = " " }, },
    { "s]", desc = "Surround with {}", icon = { icon = " " }, },
    { "s(", desc = "Surround with HTML Tag", icon = { icon = " " }, },
    { "s)", desc = "Surround with HTML Tag", icon = { icon = " " }, },
    { "st", desc = "Surround with HTML Tag", icon = { icon = " " }, },


      -- { "S",  desc = "Surround (newline)", mode = "n" },
      -- { "SS", desc = "Surround line (newline)", mode = "n" },
      -- { "dt", group = "Delete Surround", mode = "n" },
      -- { "ct", group = "Change Surround", mode = "n" },
      -- { "dt", desc = "Delete tag (dst)", mode = "n" },
      -- { "ct", desc = "Change tag (cst)", mode = "n" },
      -- { "cT", desc = "Change tag (csT)", mode = "n" },

    { "g0", hidden = true },
    { "gj", hidden = true },
    { "gk", hidden = true },
    { "g~", hidden = true },
    { "gu", hidden = true },
    { "gU", hidden = true },
    { "gD", hidden = true },
    { "gI", hidden = true },
    { "gO", hidden = true },
    -- { "gl", hidden = true },
    { "gr", hidden = true },
    { "gb", hidden = true },
    { "gnn", hidden = true },
    { "g'", hidden = true },
    { "gw", hidden = true },
    { "g`", hidden = true },
    { "g_", hidden = true },
    { "g*", hidden = true },
    { "g#", hidden = true },
    { "gc", hidden = true },
    { "g%", hidden = true },
    { "cf", hidden = true },
    { "cF", hidden = true },
    { "ct", hidden = true },
    { "cT", hidden = true },
    { "cH", hidden = true },
    { "cL", hidden = true },
    { "c[%", hidden = true },
    { "c]%", hidden = true },
    -- { "ca", hidden = true },

    { "z=", hidden = true },
    { "<leader>oi", hidden = true },
    { "<leader>d", hidden = true },
    { "<leader>df", hidden = true },
    { "<leader>dF", hidden = true },
    { "<leader>dt", hidden = true },
    { "<leader>dT", hidden = true },
    { "<leader>da", hidden = true },
    { "<leader>dg", hidden = true },
    { "<leader>dH", hidden = true },
    { "<leader>d%", hidden = true },
    { "<leader>dL", hidden = true },
    { "<leader>d[", hidden = true },
    { "<leader>d]", hidden = true },
    { "<leader>di", hidden = true },
  }
end

return M
