local M = {
  "folke/which-key.nvim",
  event = "VeryLazy",
}

function M.config()
  local which_key = require "which-key"
  which_key.setup {
    preset = "helix",
    sort = { "manual", "local", "alphanum", "mod" },
    triggers = {
      { "<auto>", mode = "nixsotc" },
      { "m", mode = "n" },
      { "s", mode = "n" },
      { "c", mode = "n" },
      { "d", mode = "n" },
      { "y", mode = "n" },
    },
    plugins = {
      marks = true,
      registers = true,
      spelling = {
        enabled = true,
        suggestions = 20,
      },
      presets = {
        operators = true,
        motions = false,
        text_objects = false,
        windows = false,
        nav = false,
        z = false,
        g = false,
      },
    },
-- check to ensure that changing window to helix is appropiate, cannot see differences
    win = {
      border = "rounded",
      no_overlap = false,
      padding = { 1, 2},
      title = false,
      title_pos = "center",
      zindex = 1000,
    },
    show_help = false,
    show_keys = false,
    disable = {
      buftypes = {},
      filetypes = { "TelescopePrompt" },
    },
  }

  local wk = require "which-key"
 
  -- icon colors
  -- azure, blue, cyan, green, grey, orange, purple, red, yellow

  wk.add {
    -- { "<leader>a", group = "AI", icon = { icon = " ", color = "blue" } },
    { "<leader>b", group = "Buffers", icon = { icon = "󰓩 ", color = "blue" }  },
    { "<leader>c", group = "Compiler", desc="Compiler", icon = { icon = "󱁤 ", color = "green" } },
    { "<leader>d", group = "Debug" },
    { "<leader>f", group = "Find", icon = { icon = " ", color = "yellow" } },
    { "<leader>g", group = "Git" },
    { "<leader>h", "<cmd>nohlsearch<CR>", desc = "NOHL", hidden = true },
    { "<leader>l", group = "LSP", icon = { icon = " ", color = "blue" }},
    { "<leader>p", group = "Plugins", icon = { icon = " ", color = "blue" } },
    { "m", group = "Macros", icon = { icon = " ", color = "green" } },
    { "<leader>e", desc = "File Explorer", icon = { icon = "" } },
    { "<leader>q", "<cmd>confirm q<CR>", desc = "Quit", icon = { icon = "󰈆", color = "red"} },
    { "<leader>o", function() vim.ui.open(vim.fn.expand("<cfile>")) end, desc = "Open URL/File", icon = { icon = " ", color = "blue" } },
    { "<leader>s", function() require("rip-substitute").sub() end, desc = "Search and Replace", mode = { "n", "x" }, icon = { icon = "", color = "blue" }, },
    { "<leader>t", desc = "Triforce Stats", "<cmd>Triforce profile<CR>", icon = { icon = "󰄩", color = "blue",}, },
    { "<leader>v", desc = "Horizontal Split", "<cmd>vsplit<CR>",  icon = { icon = "", color = "cyan",} },
    { "<leader>w", desc = "Toggle Wrap", "<cmd>lua vim.wo.wrap = not vim.wo.wrap<CR>",  icon = { icon = "󰖶 " } },
    { "<leader>/", "gcc", remap = true, desc = "Comment Line",  icon = { icon = "", color = "grey" }},
    { "<leader>/", "gc", mode = "v", remap = true, desc = "Comment Selection", icon = { icon = "", color = "grey" } },
    { "<leader>;", desc = "Terminal", "<cmd>tabnew | terminal<CR>",  icon = { icon = " ", color = "green" } },

    { "g", group = "Go to" },
    { "gd", desc = "Go to Definition", icon = { icon = "󰗚 " } },
    { "gg", desc = "Go to Top of File", icon = { icon = "󰘣 " } },
    { "gl", desc = "Show Line Diagnostics", icon = { icon = " " } },
    { "gm", desc = "Go to Middle of Line", icon = { icon = "󰘞 " } },
    { "gx", desc = "Go to File/URL", icon = { icon = "󰏋 " } },
    { "c", group = "Change" },
    { "caw", desc = "Change around Word"},
    { "ciw", desc = "Change inside Word"},
    { "cs", desc = "Change Surround" },
    { "ct", desc = "Change Surrounding HTML Tag", icon = { icon = " " }, },

    { "d", group = "Delete" },
    { "ds", desc = "Delete Surround" },
    { "dt", desc = "Delete Surrounding HTML Tag", icon = { icon = " " }, },

    { "y", group = "Yank" },
    { "ys", desc = "Yank Surround" , icon = { icon = "󰆏"} },

    { "s",  group = "Surround" },
    { "sb", desc = "Surround with ()", icon = { icon = "󰅲 " }, },
    { "s{", desc = "Surround with {}", icon = { icon = " " }, },
    { "s}", desc = "Surround with {}", icon = { icon = " " }, },
    { "s[", desc = "Surround with {}", icon = { icon = " " }, },
    { "s]", desc = "Surround with {}", icon = { icon = " " }, },
    { "s(", desc = "Surround with HTML Tag", icon = { icon = " " }, },
    { "s)", desc = "Surround with HTML Tag", icon = { icon = " " }, },
    { "st", desc = "Surround with HTML Tag", icon = { icon = " " }, },


      -- { "S",  desc = "Surround (newline)", mode = "n" },
      -- { "SS", desc = "Surround line (newline)", mode = "n" },
      -- { "dt", group = "Delete Surround", mode = "n" },
      -- { "ct", group = "Change Surround", mode = "n" },
      -- { "dt", desc = "Delete tag (dst)", mode = "n" },
      -- { "ct", desc = "Change tag (cst)", mode = "n" },
      -- { "cT", desc = "Change tag (csT)", mode = "n" },

    { "g0", hidden = true },
    { "gj", hidden = true },
    { "gk", hidden = true },
    { "g~", hidden = true },
    { "gu", hidden = true },
    { "gU", hidden = true },
    { "gD", hidden = true },
    { "gI", hidden = true },
    { "gO", hidden = true },
    { "gr", hidden = true },
    { "gb", hidden = true },
    { "gnn", hidden = true },
    { "g'", hidden = true },
    { "gw", hidden = true },
    { "g`", hidden = true },
    { "g_", hidden = true },
    { "g*", hidden = true },
    { "g#", hidden = true },
    { "gc", hidden = true },
    { "g%", hidden = true },


    { "!", hidden = true, mode = "x" },
    { "<", hidden = true, mode = "x" },
    { ">", hidden = true, mode = "x" },
    { "[", hidden = true, mode = "x" },
    { "]", hidden = true, mode = "x" },
    { "V", hidden = true, mode = "x" },
    { "c", hidden = true, mode = "x" },
    { "~", hidden = true, mode = "x" },
    { '"', hidden = true, mode = "x" },
    { "f", hidden = true, mode = "x" },
    { "F", hidden = true, mode = "x" },
    { "t", hidden = true, mode = "x" },
    { "T", hidden = true, mode = "x" },
    { "a", hidden = true, mode = "x" },
    { "g", hidden = true, mode = "x" },
    { "i", hidden = true, mode = "x" },
    { "j", hidden = true, mode = "x" },
    { "k", hidden = true, mode = "x" },
    { "l", hidden = true, mode = "x" },
    { "H", hidden = true, mode = "x" },
    { "J", hidden = true, mode = "x" },
    { "K", hidden = true, mode = "x" },
    { "L", hidden = true, mode = "x" },
    { "m", hidden = true, mode = "x" },
    { "p", hidden = true, mode = "x" },
    { "Q", hidden = true, mode = "x" },
    { "X", hidden = true, mode = "x" },
    { "z", hidden = true, mode = "x" },
    { "#", hidden = true, mode = "x" },
    { "%", hidden = true, mode = "x" },
    { "*", hidden = true, mode = "x" },
    { "@", hidden = true, mode = "x" },
    { "<C-j>", hidden = true, mode = "x" },
    { "<C-k>", hidden = true, mode = "x" },
    { "<M-j>", hidden = true, mode = "x" },
    { "<M-j>", hidden = true, mode = "x" },
    { "<C-i>", hidden = true, mode = "x" },
    { "<M-k>", hidden = true, mode = "x" },
    { "<CR>", hidden = true, mode = "x" },

    { "cf", hidden = true },
    { "cF", hidden = true },
    { "ct", hidden = true },
    { "cT", hidden = true },
    { "cH", hidden = true },
    { "cL", hidden = true },
    { "c[%", hidden = true },
    { "c]%", hidden = true },
    -- { "ca", hidden = true },

    { "z=", hidden = true },
    { "<leader>oi", hidden = true },
    { "<leader>d", hidden = true },
    { "<leader>df", hidden = true },
    { "<leader>dF", hidden = true },
    { "<leader>dt", hidden = true },
    { "<leader>dT", hidden = true },
    { "<leader>da", hidden = true },
    { "<leader>dg", hidden = true },
    { "<leader>dH", hidden = true },
    { "<leader>d%", hidden = true },
    { "<leader>dL", hidden = true },
    { "<leader>d[", hidden = true },
    { "<leader>d]", hidden = true },
    { "<leader>di", hidden = true },
  }
end

return M
